name: Build and test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # Cancel previous running actions for the same PR
  cancel_previous:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0

  build:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false # Don't cancel other matrix jobs if one fails
      matrix:
        os: [windows-2022, ubuntu-22.04]
        include:
          - build_type: Debug
            preset: debug
          - build_type: Release
            preset: release
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Visual Studio shell
        if: runner.os == 'Windows'
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: "Install Conan and CMake"
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install --yes --no-install-recommends python3-pip cmake build-essential ninja-build g++ && sudo pip install conan==2.0.1 cmake==3.23.3
      - name: "Install Conan and CMake"
        if: runner.os == 'Windows'
        # CMake 3.25 is already included in the runner image
        run: pip install conan==2.0.1
      - name: "Setup Conan"
        run: conan profile detect --force
      - name: "Checkout sources"
        uses: actions/checkout@v3
      - name: "Setup Conan cache"
        id: "conan-cache"
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-${{ matrix.build_type }}-conan2
      - name: "Conan install: Generate the CMake configuration"
        run: |
          conan install . -s build_type=${{ matrix.build_type }} --build=missing
      - name: "CMake Configure"
        run: |
          cmake --preset conan-default
      - name: "CMake Build"
        run: |
          cmake --build --preset conan-${{ matrix.preset }}
      - name: "Compress workspace"
        run: tar -cv --exclude=workspace.tar -f workspace.tar .
      - name: "Create output artifact"
        uses: actions/upload-artifact@v3
        with:
          name: built-sources-${{ matrix.build_type }}
          path: ${{ github.workspace }}/workspace.tar

  test:
    if: github.event.pull_request.draft == false
    needs: [build]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false # Don't cancel other matrix jobs if one fails
      matrix:
        os: [windows-2022, ubuntu-22.04]
        include:
          - build_type: Debug
            preset: debug
          - build_type: Release
            preset: release
    steps:
      - name: Set up Visual Studio shell
        if: runner.os == 'Windows'
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: "Install Conan and CMake"
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install --yes --no-install-recommends python3-pip cmake build-essential ninja-build g++ && sudo pip install conan==2.0.1 cmake==3.23.3
      - name: "Install Conan and CMake"
        if: runner.os == 'Windows'
        # CMake 3.25 is already included in the runner image
        run: pip install conan==2.0.1
      - name: "Setup Conan"
        run: conan profile detect --force
      - name: "Download built sources"
        uses: actions/download-artifact@v3
        with:
          name: built-sources-${{ matrix.build_type }}
          path: ${{ github.workspace }}
      - name: "Setup Conan cache"
        id: "conan-cache"
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-${{ matrix.build_type }}-conan2
      - name: "Uncompress built sources"
        run: tar -xvf workspace.tar
      - name: "CTest tests"
        run: |
          ctest --preset conan-${{ matrix.preset }}
      - name: "Conan export-pkg test"
        run: |
          conan export-pkg .
